/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.23
 * Generated at: 2023-05-01 10:38:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"icon\" href=\"dsfsdv.png\" type=\"image/png\" sizes=\"20x20\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/signup-style.css\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<style>\r\n");
      out.write("html {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("  margin:0;\r\n");
      out.write("  padding:0;\r\n");
      out.write("  font-family: sans-serif;\r\n");
      out.write("  background: linear-gradient(#141e30, #243b55);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  width: 400px;\r\n");
      out.write("  padding: 40px;\r\n");
      out.write("  transform: translate(-50%, -50%);\r\n");
      out.write("  background: rgba(0,0,0,.5);\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  box-shadow: 0 15px 25px rgba(0,0,0,.6);\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box h2 {\r\n");
      out.write("  margin: 0 0 30px;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box .user-box {\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box .user-box input {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 10px 0;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  margin-bottom: 30px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-bottom: 1px solid #fff;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  background: transparent;\r\n");
      out.write("}\r\n");
      out.write(".login-box .user-box label {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top:0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  padding: 10px 0;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  pointer-events: none;\r\n");
      out.write("  transition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box .user-box input:focus ~ label,\r\n");
      out.write(".login-box .user-box input:valid ~ label {\r\n");
      out.write("  top: -20px;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  color: #03e9f4;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box form a {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  padding: 10px 20px;\r\n");
      out.write("  color: #03e9f4;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  transition: .5s;\r\n");
      out.write("  margin-top: 40px;\r\n");
      out.write("  letter-spacing: 4px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box a:hover {\r\n");
      out.write("  background: #03e9f4;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  box-shadow: 0 0 5px #03e9f4,\r\n");
      out.write("              0 0 25px #03e9f4,\r\n");
      out.write("              0 0 50px #03e9f4,\r\n");
      out.write("              0 0 100px #03e9f4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box a span {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box a span:nth-child(1) {\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: -100%;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("  background: linear-gradient(90deg, transparent, #03e9f4);\r\n");
      out.write("  animation: btn-anim1 1s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes btn-anim1 {\r\n");
      out.write("  0% {\r\n");
      out.write("    left: -100%;\r\n");
      out.write("  }\r\n");
      out.write("  50%,100% {\r\n");
      out.write("    left: 100%;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box a span:nth-child(2) {\r\n");
      out.write("  top: -100%;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  width: 2px;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  background: linear-gradient(180deg, transparent, #03e9f4);\r\n");
      out.write("  animation: btn-anim2 1s linear infinite;\r\n");
      out.write("  animation-delay: .25s\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes btn-anim2 {\r\n");
      out.write("  0% {\r\n");
      out.write("    top: -100%;\r\n");
      out.write("  }\r\n");
      out.write("  50%,100% {\r\n");
      out.write("    top: 100%;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box a span:nth-child(3) {\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  right: -100%;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("  background: linear-gradient(270deg, transparent, #03e9f4);\r\n");
      out.write("  animation: btn-anim3 1s linear infinite;\r\n");
      out.write("  animation-delay: .5s\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes btn-anim3 {\r\n");
      out.write("  0% {\r\n");
      out.write("    right: -100%;\r\n");
      out.write("  }\r\n");
      out.write("  50%,100% {\r\n");
      out.write("    right: 100%;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box a span:nth-child(4) {\r\n");
      out.write("  bottom: -100%;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  width: 2px;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  background: linear-gradient(360deg, transparent, #03e9f4);\r\n");
      out.write("  animation: btn-anim4 1s linear infinite;\r\n");
      out.write("  animation-delay: .75s\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes btn-anim4 {\r\n");
      out.write("  0% {\r\n");
      out.write("    bottom: -100%;\r\n");
      out.write("  }\r\n");
      out.write("  50%,100% {\r\n");
      out.write("    bottom: 100%;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id='container'>\r\n");
      out.write("<div class=\"login-box\">\r\n");
      out.write("  <h2>Login</h2>\r\n");
      out.write("  <form action=\"loginAction.jsp\" method=\"post\">\r\n");
      out.write("    <div class=\"user-box\">\r\n");
      out.write("      <input type=\"email\" name=\"email\" required=\"\">\r\n");
      out.write("      <label>Email</label>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"user-box\">\r\n");
      out.write("      <input type=\"password\" name=\"password\" required=\"\">\r\n");
      out.write("      <label>Password</label>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("           <input type=\"submit\" value=Submit>\r\n");
      out.write("   	      <h2><a href=\"signup.jsp\">SignUp</a></h2>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  ");

  
  String msg=request.getParameter("msg");
  if("notexist".equals(msg)){
  
      out.write("\r\n");
      out.write("  <h1>Incorrect Username or Password</h1>\r\n");
} 
      out.write('\r');
      out.write('\n');

if("invalid".equals(msg)){

      out.write("\r\n");
      out.write("<h1>Some thing Went Wrong! Try Again !</h1>\r\n");
/*created and designed by AD Singh -- downloaded from http://projects.adsingh.net/*/} 
      out.write("\r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
